version: '3'

services:
  blog:
    image: jekimager/blog-client
    environment:
      - PORT=4173
      - ORIGIN=${ORIGIN}
    build:
      context: .
      args:
        API_URL: ${API_URL}
    ports:
      - "8000:4173"
    restart: always
