version: '3'

services:
  blog:
    image: jekimager/blog-client
    environment:
      - PORT=1234
      - HOST=0.0.0.0
      - ORIGIN=${ORIGIN}
    build:
      context: .
      args:
        PUBLIC_API_URL: ${API_URL}
        API_URL: ${API_URL}
    ports:
      - "8000:1234"
    restart: always
