version: '3'

services:
  blog:
    image: jekimager/blog-client
    environment:
      - API_URL=${API_URL}
      - PORT=4173
    build:
      context: .
      dockerfile: Dockerfile.blog
      args:
        DOCKER_BUILDKIT: 1
    ports:
      - "80:4173"
